apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-post-deployment
spec:
  replicas: 1            # start with 1 pod
  selector:
    matchLabels:
      app: get-post
  template:
    metadata:
      labels:
        app: get-post
    spec:
      containers:
      - name: get-post-container
        image: aarthidevops/get-post-file:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
