apiVersion: v1
kind: Service
metadata:
  name: student-app-service
spec:
  type: NodePort
  selector:
    app: get-post        # MUST MATCH POD
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000   # or 80 based on your app
      nodePort: 30007
